# =====================================================================
#  auth-service  ·  PERFIL docker (localhost -> nombres de contenedor)
# =====================================================================
spring.config.import=optional:configserver:http://config-server:8888
