spring.application.name=config-server
server.port=8888

# Backend NATIVE: sirve la config desde la carpeta classpath:/config
# (En produccion se usaria Git: spring.cloud.config.server.git.uri=...)
spring.cloud.config.server.git.uri=https://github.com/wlopezdlm/Sistema-de-Biblioteca---Java-Microservicios
spring.cloud.config.server.git.search-paths=walter-lopez-examen-microservicios/service-configuration
spring.cloud.config.server.git.default-label=main

spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true
#spring.cloud.config.server.git.username=
#spring.cloud.config.server.git.password=

# Actuator para el healthcheck del docker-compose
management.endpoints.web.exposure.include=health,info
