spring.application.name=libros-service
server.port=8081

#spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=configserver:http://localhost:8888
spring.profiles.active=dev